/**
 * scripts/apply-config.mjs
 *
 * Reads birthday.config.js and generates five files:
 *
 *   public/index.html        — from public/index.template.html
 *   public/calendar.html     — from public/calendar.template.html
 *   public/config.js         — window.BIRTHDAY_CONFIG for runtime JS
 *   public/app.js            — extracted inline app script from index.template.html
 *   public/calendar-app.js   — extracted inline app script from calendar.template.html
 *
 * PLACEHOLDER CONVENTION
 * ──────────────────────
 * Templates use {{section.key}} tokens that match the dot-path into the
 * config object, e.g. {{site.title}}, {{locale.htmlLang}}.
 *
 * The template files (*.template.html) are the edited source. The generated
 * *.html files are outputs — do not edit them directly; they will be
 * overwritten on the next run.
 *
 * IDEMPOTENCY
 * ───────────
 * Because we always render from the template source (not from a previously
 * generated file), running this script twice produces identical output.
 * Vercel runs the buildCommand on every deploy, so this property is required.
 *
 * USAGE
 *   node scripts/apply-config.mjs
 *   npm run config
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// ── Load config ────────────────────────────────────────────────────────────
const { default: config } = await import(`${ROOT}/birthday.config.js`);

// ── Flatten config into a token map { 'site.title': "Sam's Birthday Week", … } ───
function flatten(obj, prefix = '') {
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}.${k}` : k;
    if (v !== null && typeof v === 'object' && !Array.isArray(v)) {
      Object.assign(out, flatten(v, key));
    } else {
      out[key] = String(v);
    }
  }
  return out;
}
const tokens = flatten(config);

// ── Replace all {{key}} occurrences in a string ────────────────────────────
function applyTokens(src) {
  return src.replace(/\{\{([\w.]+)\}\}/g, (match, key) => {
    if (Object.prototype.hasOwnProperty.call(tokens, key)) {
      return tokens[key];
    }
    // Unknown placeholder — leave it intact and warn so the operator notices.
    console.warn(`  [WARN] Unknown placeholder: {{${key}}} — left as-is`);
    return match;
  });
}

// ── HTML-attribute-quote safety check ─────────────────────────────────────
// Detects a `"` inside a config value that is destined for a double-quoted
// HTML attribute (e.g. <meta content="…">). Such a value would silently
// break attribute quoting and the JS-parse self-test would NOT catch it.
// We check the token map at build time, before rendering, so the error
// names the offending key rather than pointing at broken HTML.
function checkAttributeQuoteSafety() {
  // These token keys are rendered into double-quoted HTML attribute values.
  const attributeKeys = [
    'site.ogTitle',
    'site.ogDescription',
    'site.ogImageAlt',
    'site.ogImageUrl',
    'site.domain',
    'calendar.ogTitle',
  ];
  const offending = [];
  for (const key of attributeKeys) {
    const val = tokens[key];
    if (val !== undefined && val.includes('"')) {
      offending.push(`  ${key}: ${JSON.stringify(val)}`);
    }
  }
  if (offending.length > 0) {
    console.error('  [FAIL] Attribute-quote safety: the following config values contain an unescaped `"` and would break HTML attribute quoting:');
    offending.forEach(line => console.error(line));
    console.error('  Fix: remove or escape the `"` in birthday.config.js for those keys.');
    process.exit(1);
  }
}
checkAttributeQuoteSafety();

// ── Auto-generated HTML banner ─────────────────────────────────────────────
const HTML_BANNER_INDEX    = '<!-- AUTO-GENERATED by scripts/apply-config.mjs — edit public/index.template.html, not this file. -->\n';
const HTML_BANNER_CALENDAR = '<!-- AUTO-GENERATED by scripts/apply-config.mjs — edit public/calendar.template.html, not this file. -->\n';

// ── JS banner for extracted external script files ──────────────────────────
function jsScriptBanner(templateName) {
  return `// AUTO-GENERATED by scripts/apply-config.mjs — edit public/${templateName}, not this file.\n`;
}

// ── Extract the single large inline <script> (no src=) from an HTML string ──
// Finds the first <script> tag with no src= attribute, extracts its inner JS
// body, and replaces the whole block with a <script src="…"> reference.
// Returns { html, scriptBody } where scriptBody is the raw JS (without tags).
// Assumption (verified): neither template contains a literal </script> inside
// the JS body, so a straightforward split on the closing tag is safe.
function extractInlineScript(html, srcRef) {
  // Match an opening <script> that has NO src= attribute, capturing the body.
  // We use a two-step approach: find the opening tag, then scan for </script>.
  const openTagRe = /<script(?![^>]*\bsrc\s*=)[^>]*>/i;
  const openMatch = openTagRe.exec(html);
  if (!openMatch) {
    throw new Error(`extractInlineScript: no inline <script> (without src=) found; cannot extract to ${srcRef}`);
  }
  const openTagEnd = openMatch.index + openMatch[0].length;
  const closeTag = '</script>';
  const closeIndex = html.indexOf(closeTag, openTagEnd);
  if (closeIndex === -1) {
    throw new Error(`extractInlineScript: found opening <script> but no matching </script> for ${srcRef}`);
  }
  const scriptBody = html.slice(openTagEnd, closeIndex);
  const before = html.slice(0, openMatch.index);
  const after  = html.slice(closeIndex + closeTag.length);
  const replacement = `<script src="${srcRef}"></script>`;
  return { html: before + replacement + after, scriptBody };
}

// ── Process one template → output pair ────────────────────────────────────
// opts.extractScript: { scriptOutputPath, srcRef, templateName }
//   If provided, the single inline <script> (no src=) is extracted to
//   scriptOutputPath and replaced in the HTML with <script src="srcRef">.
function processTemplate(templatePath, outputPath, label, banner, opts = {}) {
  let src;
  try {
    src = readFileSync(templatePath, 'utf8');
  } catch (err) {
    if (err.code === 'ENOENT') {
      console.log(`  [SKIP] ${label}: template not found at ${templatePath}`);
      return { replaced: 0, skipped: true };
    }
    throw err;
  }

  let result = applyTokens(src);

  // Count how many substitutions were actually made (each unique match counts once per occurrence)
  const hits = (src.match(/\{\{[\w.]+\}\}/g) || []).length;

  // Extract inline app script if requested
  if (opts.extractScript) {
    const { scriptOutputPath, srcRef, templateName } = opts.extractScript;
    const extracted = extractInlineScript(result, srcRef);
    result = extracted.html;
    const jsContent = jsScriptBanner(templateName) + extracted.scriptBody;
    writeFileSync(scriptOutputPath, jsContent, 'utf8');
    console.log(`  [OK]   ${templateName} script → ${scriptOutputPath.replace(ROOT, '.')} (extracted inline app script)`);
  }

  // Prepend the auto-generated banner as the very first line
  writeFileSync(outputPath, (banner || '') + result, 'utf8');
  console.log(`  [OK]   ${label} → ${outputPath.replace(ROOT, '.')} (${hits} placeholder${hits !== 1 ? 's' : ''} applied)`);
  return { replaced: hits, skipped: false };
}

// ── Write public/config.js ─────────────────────────────────────────────────
// All fields in birthday.config.js are public-facing copy — none are secrets.
// This makes the full config available to frontend JS at window.BIRTHDAY_CONFIG.
function writeRuntimeConfig(outputPath) {
  const json = JSON.stringify(config, null, 2);
  const content = `// AUTO-GENERATED by scripts/apply-config.mjs — do not edit directly.\n// Edit birthday.config.js and run: npm run config\nwindow.BIRTHDAY_CONFIG = ${json};\n`;
  writeFileSync(outputPath, content, 'utf8');
  console.log(`  [OK]   config.js → ${outputPath.replace(ROOT, '.')} (runtime window.BIRTHDAY_CONFIG)`);
}

// ── Main ───────────────────────────────────────────────────────────────────
console.log('\nbirthdayaas apply-config');
console.log('────────────────────────');
console.log(`  host: ${config.host.fullName} (${config.host.name}), age ${config.host.age}`);
console.log(`  site: ${config.site.title} · ${config.site.domain}`);
console.log(`  event: ${config.event.dateRange}`);
console.log('');

processTemplate(
  resolve(ROOT, 'public/index.template.html'),
  resolve(ROOT, 'public/index.html'),
  'index.html',
  HTML_BANNER_INDEX,
  {
    extractScript: {
      scriptOutputPath: resolve(ROOT, 'public/app.js'),
      srcRef: '/app.js',
      templateName: 'index.template.html',
    },
  },
);

processTemplate(
  resolve(ROOT, 'public/calendar.template.html'),
  resolve(ROOT, 'public/calendar.html'),
  'calendar.html',
  HTML_BANNER_CALENDAR,
  {
    extractScript: {
      scriptOutputPath: resolve(ROOT, 'public/calendar-app.js'),
      srcRef: '/calendar-app.js',
      templateName: 'calendar.template.html',
    },
  },
);

writeRuntimeConfig(resolve(ROOT, 'public/config.js'));

// ── Self-test: spot-check a known value in the generated index.html ────────
console.log('');
console.log('Self-test:');
const generatedIndex = readFileSync(resolve(ROOT, 'public/index.html'), 'utf8');
const checks = [
  ['<title>', `<title>${config.site.title}</title>`],
  ['og:title', `content="${config.site.ogTitle}"`],
  ['lang attr', `lang="${config.locale.htmlLang}"`],
  ['og:url', `content="${config.site.domain}"`],
  ['og:image', `content="${config.site.ogImageUrl}"`],
];
let allPass = true;
for (const [name, needle] of checks) {
  const pass = generatedIndex.includes(needle);
  console.log(`  ${pass ? '✓' : '✗'} ${name}: ${needle.slice(0, 60)}`);
  if (!pass) allPass = false;
}

const generatedCalendar = readFileSync(resolve(ROOT, 'public/calendar.html'), 'utf8');
const calChecks = [
  ['calendar <title>', `<title>${config.calendar.title}</title>`],
  ['calendar og:title', `content="${config.calendar.ogTitle}"`],
];
for (const [name, needle] of calChecks) {
  const pass = generatedCalendar.includes(needle);
  console.log(`  ${pass ? '✓' : '✗'} ${name}: ${needle.slice(0, 60)}`);
  if (!pass) allPass = false;
}

// Check no unresolved placeholders remain in generated files
for (const [filename, content] of [['index.html', generatedIndex], ['calendar.html', generatedCalendar]]) {
  const remaining = content.match(/\{\{[\w.]+\}\}/g) || [];
  if (remaining.length > 0) {
    console.log(`  ✗ unresolved placeholders in ${filename}: ${remaining.join(', ')}`);
    allPass = false;
  } else {
    console.log(`  ✓ no unresolved placeholders in ${filename}`);
  }
}

// Check that the generated HTML files contain NO remaining inline <script> bodies
// (they should only have <script src="…"> references after extraction)
for (const [name, content] of [['index.html', generatedIndex], ['calendar.html', generatedCalendar]]) {
  const scriptRe = /<script(?:\s[^>]*)?>([^]*?)<\/script>/gi;
  let match;
  let foundInline = false;
  while ((match = scriptRe.exec(content)) !== null) {
    const body = match[1];
    if (body.trim()) {
      foundInline = true;
      allPass = false;
      console.log(`  ✗ unexpected inline script body remains in ${name} (should have been extracted)`);
    }
  }
  if (!foundInline) {
    console.log(`  ✓ no inline script bodies in ${name} (all extracted to external files)`);
  }
}

// Parse-check the extracted external app script files
for (const [name, path] of [['app.js', resolve(ROOT, 'public/app.js')], ['calendar-app.js', resolve(ROOT, 'public/calendar-app.js')]]) {
  let jsContent;
  try {
    jsContent = readFileSync(path, 'utf8');
  } catch (e) {
    allPass = false;
    console.log(`  ✗ ${name}: file not found at ${path}`);
    continue;
  }
  try {
    // eslint-disable-next-line no-new-func
    new Function(jsContent);
    console.log(`  ✓ ${name} parses as valid JS`);
  } catch (e) {
    allPass = false;
    console.log(`  ✗ ${name} fails to parse: ${e.message}`);
    // Scan flattened config values for quote/backtick that could have broken the script.
    const suspiciousKeys = Object.entries(tokens)
      .filter(([, v]) => v.includes("'") || v.includes('`'))
      .map(([k]) => k);
    if (suspiciousKeys.length > 0) {
      console.log(`  Hint: a config value contains a quote or backtick that may have broken the script. Check these keys in birthday.config.js / birthday.strings.js:`);
      suspiciousKeys.forEach(k => console.log(`    ${k}: ${JSON.stringify(tokens[k])}`));
    }
  }
}

// ── Date-consistency WARNING ───────────────────────────────────────────────
// If config.event.dateRange doesn't contain the start year, warn the forker
// that the prose date strings may be out of sync with the ISO dates.
// This is a non-fatal warning — we never block the build on it.
try {
  const startYear = config.event.startDate ? config.event.startDate.slice(0, 4) : null;
  if (startYear && !String(config.event.dateRange || '').includes(startYear)) {
    console.log(`  [WARN] Date consistency: event.dateRange ("${config.event.dateRange}") does not contain the start year ${startYear} from event.startDate ("${config.event.startDate}"). Your prose date strings may be out of sync with the ISO dates — update event.dateRange / dateRangeShort / dateRangeFull / monthYear in birthday.config.js.`);
  }
} catch (_) { /* non-fatal */ }

console.log('');
console.log(allPass ? 'Done. All checks passed.' : 'Done with warnings — see ✗ above.');
console.log('');

if (!allPass) process.exit(1);
