/**
 * scripts/apply-config.mjs
 *
 * Reads birthday.config.js and generates three files:
 *
 *   public/index.html        — from public/index.template.html
 *   public/calendar.html     — from public/calendar.template.html
 *   public/config.js         — window.BIRTHDAY_CONFIG for runtime JS
 *
 * PLACEHOLDER CONVENTION
 * ──────────────────────
 * Templates use {{section.key}} tokens that match the dot-path into the
 * config object, e.g. {{site.title}}, {{locale.htmlLang}}.
 *
 * The template files (*.template.html) are the edited source. The generated
 * *.html files are outputs — do not edit them directly; they will be
 * overwritten on the next run.
 *
 * IDEMPOTENCY
 * ───────────
 * Because we always render from the template source (not from a previously
 * generated file), running this script twice produces identical output.
 * Vercel runs the buildCommand on every deploy, so this property is required.
 *
 * USAGE
 *   node scripts/apply-config.mjs
 *   npm run config
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// ── Load config ────────────────────────────────────────────────────────────
const { default: config } = await import(`${ROOT}/birthday.config.js`);

// ── Flatten config into a token map { 'site.title': "Sam's Birthday Week", … } ───
function flatten(obj, prefix = '') {
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}.${k}` : k;
    if (v !== null && typeof v === 'object' && !Array.isArray(v)) {
      Object.assign(out, flatten(v, key));
    } else {
      out[key] = String(v);
    }
  }
  return out;
}
const tokens = flatten(config);

// ── Replace all {{key}} occurrences in a string ────────────────────────────
function applyTokens(src) {
  return src.replace(/\{\{([\w.]+)\}\}/g, (match, key) => {
    if (Object.prototype.hasOwnProperty.call(tokens, key)) {
      return tokens[key];
    }
    // Unknown placeholder — leave it intact and warn so the operator notices.
    console.warn(`  [WARN] Unknown placeholder: {{${key}}} — left as-is`);
    return match;
  });
}

// ── Process one template → output pair ────────────────────────────────────
function processTemplate(templatePath, outputPath, label) {
  let src;
  try {
    src = readFileSync(templatePath, 'utf8');
  } catch (err) {
    if (err.code === 'ENOENT') {
      console.log(`  [SKIP] ${label}: template not found at ${templatePath}`);
      return { replaced: 0, skipped: true };
    }
    throw err;
  }

  const result = applyTokens(src);

  // Count how many substitutions were actually made (each unique match counts once per occurrence)
  const hits = (src.match(/\{\{[\w.]+\}\}/g) || []).length;

  writeFileSync(outputPath, result, 'utf8');
  console.log(`  [OK]   ${label} → ${outputPath.replace(ROOT, '.')} (${hits} placeholder${hits !== 1 ? 's' : ''} applied)`);
  return { replaced: hits, skipped: false };
}

// ── Write public/config.js ─────────────────────────────────────────────────
// All fields in birthday.config.js are public-facing copy — none are secrets.
// This makes the full config available to frontend JS at window.BIRTHDAY_CONFIG.
function writeRuntimeConfig(outputPath) {
  const json = JSON.stringify(config, null, 2);
  const content = `// AUTO-GENERATED by scripts/apply-config.mjs — do not edit directly.\n// Edit birthday.config.js and run: npm run config\nwindow.BIRTHDAY_CONFIG = ${json};\n`;
  writeFileSync(outputPath, content, 'utf8');
  console.log(`  [OK]   config.js → ${outputPath.replace(ROOT, '.')} (runtime window.BIRTHDAY_CONFIG)`);
}

// ── Main ───────────────────────────────────────────────────────────────────
console.log('\nbirthdayaas apply-config');
console.log('────────────────────────');
console.log(`  host: ${config.host.fullName} (${config.host.name}), age ${config.host.age}`);
console.log(`  site: ${config.site.title} · ${config.site.domain}`);
console.log(`  event: ${config.event.dateRange}`);
console.log('');

processTemplate(
  resolve(ROOT, 'public/index.template.html'),
  resolve(ROOT, 'public/index.html'),
  'index.html',
);

processTemplate(
  resolve(ROOT, 'public/calendar.template.html'),
  resolve(ROOT, 'public/calendar.html'),
  'calendar.html',
);

writeRuntimeConfig(resolve(ROOT, 'public/config.js'));

// ── Self-test: spot-check a known value in the generated index.html ────────
console.log('');
console.log('Self-test:');
const generatedIndex = readFileSync(resolve(ROOT, 'public/index.html'), 'utf8');
const checks = [
  ['<title>', `<title>${config.site.title}</title>`],
  ['og:title', `content="${config.site.ogTitle}"`],
  ['lang attr', `lang="${config.locale.htmlLang}"`],
  ['og:url', `content="${config.site.domain}"`],
  ['og:image', `content="${config.site.ogImageUrl}"`],
];
let allPass = true;
for (const [name, needle] of checks) {
  const pass = generatedIndex.includes(needle);
  console.log(`  ${pass ? '✓' : '✗'} ${name}: ${needle.slice(0, 60)}`);
  if (!pass) allPass = false;
}

const generatedCalendar = readFileSync(resolve(ROOT, 'public/calendar.html'), 'utf8');
const calChecks = [
  ['calendar <title>', `<title>${config.calendar.title}</title>`],
  ['calendar og:title', `content="${config.calendar.ogTitle}"`],
];
for (const [name, needle] of calChecks) {
  const pass = generatedCalendar.includes(needle);
  console.log(`  ${pass ? '✓' : '✗'} ${name}: ${needle.slice(0, 60)}`);
  if (!pass) allPass = false;
}

// Check no unresolved placeholders remain in generated files
for (const [filename, content] of [['index.html', generatedIndex], ['calendar.html', generatedCalendar]]) {
  const remaining = content.match(/\{\{[\w.]+\}\}/g) || [];
  if (remaining.length > 0) {
    console.log(`  ✗ unresolved placeholders in ${filename}: ${remaining.join(', ')}`);
    allPass = false;
  } else {
    console.log(`  ✓ no unresolved placeholders in ${filename}`);
  }
}

// Check all inline <script> blocks in generated HTML files parse as valid JS
for (const [name, content] of [['index.html', generatedIndex], ['calendar.html', generatedCalendar]]) {
  const scriptRe = /<script(?:\s[^>]*)?>([^]*?)<\/script>/gi;
  let match;
  let allScriptsOk = true;
  while ((match = scriptRe.exec(content)) !== null) {
    const body = match[1];
    // Skip empty blocks and external src= blocks (no inline body to parse)
    if (!body.trim()) continue;
    try {
      // eslint-disable-next-line no-new-func
      new Function(body);
    } catch (e) {
      allPass = false;
      allScriptsOk = false;
      console.log(`  ✗ generated inline script fails to parse in ${name}: ${e.message}`);
    }
  }
  if (allScriptsOk) {
    console.log(`  ✓ inline scripts parse OK in ${name}`);
  }
}

console.log('');
console.log(allPass ? 'Done. All checks passed.' : 'Done with warnings — see ✗ above.');
console.log('');

if (!allPass) process.exit(1);
